RockPaperScissorsApp/Models/ErrorViewModel.cs
using System;

namespace RockPaperScissorsApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RockPaperScissorsApp/Models/GameViewModel.cs
using System.Collections.Generic;
using System.Linq;
using RockPaperScissors.Entities;

namespace RockPaperScissorsApp.Models
{
    public class GameViewModel
    {
        public List<Player> Players { get; set; }
        public Game Game { get;  set; }
    }
}

RockPaperScissorsApp/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RockPaperScissors;
using RockPaperScissors.Communications;
using RockPaperScissors.DbInteractions;
using RockPaperScissors.Entities;
using RockPaperScissors.Entities.Enums;
using RockPaperScissorsApp.Models;
using SQLitePCL;

namespace RockPaperScissorsApp.Controllers
{

    public class GameController : Controller
    {
        private readonly GameRules _rules;
        private readonly GameContext _context;

        private readonly IMediator _mediator;

        public GameController(GameRules rules,
            GameContext _context,
            IMediator mediator)
        {
            _rules = rules;
            this._context = _context;
            _mediator = mediator;
        }

        // GET: CreateGame
        [HttpGet]
        public IActionResult StartGame()
        {
            ViewBag.Players = new SelectList(_context.Players.ToList(), "PlayerId", "PlayerName");
            return View();
        }

        // Post: CreateGame
        [HttpPost]
        public async Task<IActionResult> StartGame(GameRequest gameRequest, Game game)
        {
            var response = await _mediator.Send(gameRequest);
            return RedirectToAction("PlayGame", new { id = response.GameId });
        }

        // GET: Play
        [HttpGet("PlayGame")]
        public IActionResult PlayGame(int id)
        {
            var gameViewModel = GameDetails(id);

            return View(gameViewModel);
        }

        private GameViewModel GameDetails(int id)
        {
            var gameViewModel = new GameViewModel
            {
                Game = _context.Games.FirstOrDefault(x => x.GameId == id)
            };
            gameViewModel.Players = _context.Players.Where(x => gameViewModel.Game.Player1 == x.PlayerId
            || gameViewModel.Game.Player2 == x.PlayerId).ToList();
            return gameViewModel;
        }

        [HttpPost]
        public IActionResult Play([FromForm]Choice humanChoice, [FromForm]GameViewModel gameModel)
        {
            var choices = _rules.PlayGame(humanChoice, gameModel.Game.GameId);
            return RedirectToAction("PlayGame", new { id = gameModel.Game.GameId });
        }

        // GET: Game/Details/5
        public ActionResult PlayScreen()
        {
            return View();
        }

        // GET: Game/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Game/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Game/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Game/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Game/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Game/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RockPaperScissorsApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RockPaperScissorsApp.Models;

namespace RockPaperScissorsApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RockPaperScissorsApp/Controllers/PalyersController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using RockPaperScissors.DbInteractions;
using RockPaperScissors.Entities;
using RockPaperScissors.Entities.IEntities;

namespace RockPaperScissorsWebApi.Controllers
{
    public class PlayersController : Controller
    {
        private readonly GameContext _context;

        public PlayersController(GameContext context)
        {
            _context = context;
        }

        // GET api/values
        [HttpGet]
        public IActionResult Index()
        {
            var players = _context.Players.ToList();
            return View(players);
        }

        // GET api/values/5
        [HttpGet("Players/Player/{id}")]
        public IActionResult Get(int id)
        {
            var player = _context.Players.Find(id);
            if (player == null)
                return NotFound();
            return View(player);
        }

        // Get 
        [HttpGet("Players/Create")]
        public IActionResult CreateNewPlayer()
        {
            return View(new Player());
        }
        // POST api/values
        [HttpPost("Players/Create")]
        public IActionResult CreateNewPlayer(Player value)
        {
            value.PlayerCreatedDate=DateTime.Now;
            _context.Players.Add(value);
            _context.SaveChanges();

            return RedirectToAction("Player", new { id = value.PlayerId });
        }

        // PUT api/values/5
        [HttpPut("Players/edit/{id}")]
        public IActionResult Update(int id, [FromBody]Player value)
        {
            var player = _context.Players.Find(id);
            if (player == null)
            {
                return NotFound();
            }

            player.PlayerType = value.PlayerType;
            player.PlayerChoice = value.PlayerChoice;

            _context.Players.Update(player);
            _context.SaveChanges();
            return RedirectToAction("Player",new {id=value.PlayerId});
        }

        [HttpGet("Players/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            var player = _context.Players.Find(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        [HttpPost("Players/Delete/{id}")]
        public IActionResult DeletePlayer(int id)
        {
            var player = _context.Players.Find(id);
            if (player == null)
            {
                return NotFound();
            }

            _context.Players.Remove(player);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RockPaperScissorsApp/Views/Game/Play.cshtml
@using RockPaperScissors.Entities.Enums
@model IEnumerable<RockPaperScissors.Entities.Player>

@{
    ViewData["Title"] = "Play";
}

<h2>Play</h2>

<h4>Player</h4>
<hr />


<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlayerType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerCreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerChoice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerCreatedDate)
                </td>
                @if (item.PlayerType == PlayerType.Human)
                {
                    <form asp-action="Play">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="@item.PlayerId" />

                        <td>
                            <div class="form-group">
                                <label asp-for="@item.PlayerChoice" class="control-label"></label>
                                @Html.DropDownList("choice", Html.GetEnumSelectList<Choice>(), "select")
                                <span asp-validation-for="@item.PlayerChoice" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Play" class="btn btn-default"/>
                            </div>
                        </td>

                    </form>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.PlayerChoice)
                    </td>
                }
              
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RockPaperScissorsApp/Views/Game/PlayGame.cshtml
@using Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments
@using RockPaperScissors.Entities.Enums
@using RockPaperScissorsApp.Models
@model GameViewModel

@{
    ViewData["Title"] = "PlayGame";
}

<h2>PlayGame</h2>
<style>
    #results {
       width: 100%
    }
</style>
<div>
    <div class="col-lg-12 table-bordered border">
        <div  class="col-lg-3">Number Of Tries:</div>
        <div  class="col-lg-3"> @Model.Game.NumberOfTries</div>
        @{
            var player1 = Model.Players.FirstOrDefault(x => x.PlayerId == Model.Game.Player1);
            var player2 = Model.Players.FirstOrDefault(x => x.PlayerId == Model.Game.Player2);
            if (Model.Game.NumberOfTries == 0)
            {
                if (player1?.Score > player2?.Score) {
                    <div  class="col-lg-3">@player1.PlayerName Won the Game</div>
                }

                else if (player2?.Score > player1?.Score) {
                    <div  class="col-lg-3">@player2.PlayerName  Won the Game</div>
                }
                else if (player2?.Score == player1?.Score)
                {
                    <div class="col-lg-3">This is a draw. both players have equal score!!</div>
                }

            }
        }
      
    </div>

    <table class="table">

        <thead>
            <tr>
                <th>
                    Player Type
                </th>
                <th>
                    Player Name
                </th>

                <th>
                    Player Choice
                </th>
                <th>
                    Player Score
                </th>
               @if (Model.Game.NumberOfTries >0)
                {
                <th>
                    Chose
                </th>
                }
                <th></th>
            </tr>
        </thead>
        <tbody>
            <form asp-action="Play">
                <input type="hidden" asp-for="@Model.Game.GameId" />
                <input type="hidden" asp-for="@Model.Players" />
                @for (int i = 0; i < Model.Players.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => modelItem.Players[i].PlayerType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => modelItem.Players[i].PlayerName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => Model.Players[i].PlayerChoice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Players[i].Score)
                        </td>
                        <input type="hidden" asp-for="@Model.Players[i].PlayerId" />

                        @if (Model.Players[i].PlayerType == PlayerTypeEnum.Human && Model.Game.NumberOfTries >0)
                        {

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <td>
                                <div class="form-group">
                                    @Html.DropDownList("humanChoice", Html.GetEnumSelectList<Choice>(), "select")
                                    <span asp-validation-for="@Model.Players[i].PlayerChoice" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Play" OnClick="myFunction()" class="btn btn-default" />
                                </div>
                            </td>
                        }
                        else
                        {
                            <td>
                                &nbsp;&nbsp;
                            </td>
                        }


                    </tr>
                }
            </form>
        </tbody>
    </table>

</div>


RockPaperScissorsApp/Views/Game/StartGame.cshtml
@model RockPaperScissors.Entities.Game

@{
    ViewData["Title"] = "StartGame";
}

<h2>StartGame</h2>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="StartGame">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Player1" class="control-label"></label>
                @Html.DropDownListFor(x=>x.Player1, ViewBag.Players as SelectList)
                <span asp-validation-for="Player1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Player2" class="control-label"></label>
                @Html.DropDownListFor(x=>x.Player2, ViewBag.Players as SelectList)
                <span asp-validation-for="Player2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Start Game" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RockPaperScissorsApp/Views/Players/CreateNewPlayer.cshtml
@using RockPaperScissors.Entities.Enums
@model RockPaperScissors.Entities.Player

@{
    ViewData["Title"] = "CreateNewPlayer";
}

<h2>CreateNewPlayer</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlayerType" class="control-label"></label>
                <select asp-for="PlayerType" asp-items="Html.GetEnumSelectList<PlayerTypeEnum>()" class="form-control"></select>
                <span asp-validation-for="PlayerType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerName" class="control-label"></label>
                <input asp-for="PlayerName" class="form-control" />
                <span asp-validation-for="PlayerName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RockPaperScissorsApp/Views/Players/Delete.cshtml
@model RockPaperScissors.Entities.Player

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlayerType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayerCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerCreatedDate)
        </dd>
       
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlayerId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RockPaperScissorsApp/Views/Players/Get.cshtml
@model RockPaperScissors.Entities.Player

@{
    ViewData["Title"] = "Get";
}

<h2>Get</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlayerType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayerCreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayerCreatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PlayerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RockPaperScissorsApp/Views/Players/Index.cshtml
@model IEnumerable<RockPaperScissors.Entities.Player>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PlayerType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlayerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlayerCreatedDate)
                </th>
                
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerCreatedDate)
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.PlayerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PlayerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PlayerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RockPaperScissorsApp/Views/Players/Update.cshtml
@model RockPaperScissors.Entities.Player

@{
    ViewData["Title"] = "Update";
}

<h2>Update</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlayerId" />
            <div class="form-group">
                <label asp-for="PlayerType" class="control-label"></label>
                <select asp-for="PlayerType" class="form-control"></select>
                <span asp-validation-for="PlayerType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerName" class="control-label"></label>
                <input asp-for="PlayerName" class="form-control" />
                <span asp-validation-for="PlayerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerCreatedDate" class="control-label"></label>
                <input asp-for="PlayerCreatedDate" class="form-control" />
                <span asp-validation-for="PlayerCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RockPaperScissorsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RockPaperScissorsApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RockPaperScissorsApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Players" asp-action="Index">Add Players</a></li>
                    <li><a asp-area="" asp-controller="Game" asp-action="StartGame">Play</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RockPaperScissorsApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>